name:                trial-chain
version:             0.1.0.0
github:              "raduom/trial-chain"
license:             BSD3
author:              "Radu Ometita"
maintainer:          "radu.ometita@gmail.com"
copyright:           "2022 Radu Ometita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trial-chain#readme>

dependencies:
- base >= 4.7 && < 5
- safe

default-extensions:
- NumericUnderscores
- GeneralizedNewtypeDeriving

library:
  source-dirs: src

executables:
  trial-chain-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - trial-chain

tests:
  trial-chain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - trial-chain
    - either
    - QuickCheck
